# Generated by Django 5.1.6 on 2025-02-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='publicado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_publicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categorias',
            field=models.ManyToManyField(to='anuncio.categoria'),
        ),
        migrations.AddField(
            model_name='ofertaanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='anuncio.anuncio'),
        ),
        migrations.AddField(
            model_name='ofertaanuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='oferta_ganadora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_ganadora', to='anuncio.ofertaanuncio'),
        ),
        migrations.AddField(
            model_name='seguimientoanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='anuncio.anuncio'),
        ),
        migrations.AddField(
            model_name='seguimientoanuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_anuncios', to=settings.AUTH_USER_MODEL),
        ),
    ]
