# Generated by Django 5.1.6 on 2025-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='anuncio.categoria'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
